### PR TITLE
styled the button

### PR DESCRIPTION
**Pull request by guneshmunjal**

### CODE REVIEW

**Comment by guneshmunjal** [comment]
sir if i have made a mistake while pushing the code i am really very sorry because i am doing open source for the first time. if wrong please correct me

**Comment by abhishek213-alb** [comment]
@guneshmunjal please resolve conflicts

**Comment by guneshmunjal** [comment]
Kindly add hactoberfest label please

**Comment by guneshmunjal** [comment]
@abhishek213-alb add hactoberfest label

**Pull request closed without merging**
