### PR TITLE
Fixed Responsivity for all screens

### PR DESCRIPTION
**Pull request by Ritika-Agrawal811**
Worked on Issue number : #5

Let me know if anything else needs to be fixed in responsivity.

### CODE REVIEW

**Comment by abhishek213-alb** [comment]
Great 
Can you add a function by using user can direct setup a countdown from website directly

**Comment by Ritika-Agrawal811** [comment]
> Great Can you add a function by using user can direct setup a countdown from website directly

Can you please elaborate on this more?

**Comment by abhishek213-alb** [comment]
Screenshot_20221003-150509_Chrome
Sample . 
Make like this

**Comment by Ritika-Agrawal811** [comment]
> Screenshot_20221003-150509_Chrome Sample . Make like this

Okay. I am on it

**Pull request merged**
