### PR TITLE
updated footer

### PR DESCRIPTION
**Pull request by Abhinav-3359**
added social media sites

### CODE REVIEW

**Comment by Abhinav-3359** [comment]
Sir added footer as you wanted pls review

**Review by abhishek213-alb — CHANGES_REQUESTED** [review]
Hey footer should look like this 
image
not only social icons

**Comment by Abhinav-3359** [comment]
Okay sir I’ll implement

**Comment by Abhinav-3359** [comment]
sir pls review did as you wanted

**Review by abhishek213-alb — APPROVED** [review]

**Pull request merged**
